include: package:netglade_analysis/lints.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/"
    - "./build_cache/"

dart_code_metrics:
  extends:
    - package:netglade_analysis/dcm.yaml
